import { NextResponse } from "next/server";

const sounds = [
  {
    id: "1",
    title: "The Inner Core",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/1_The_Inner_Core.mp3",
  },
  {
    id: "2",
    title: "Bubbling Pools",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/2_Bubbling_Pools.mp3",
  },
  {
    id: "3",
    title: "March of the Faithful",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/3_The_March_of_the_Faithful.mp3",
  },
  {
    id: "4",
    title: "Solemn Vow",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/4_Solemn_Vow-a.mp3",
  },
  {
    id: "5",
    title: "Desert Bazaar",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/5_Desert_Bazaar.mp3",
  },
  {
    id: "6",
    title: "Abyssal Gaze",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/6_Abyssal_Gaze.mp3",
  },
  {
    id: "7",
    title: "The Desert Awaits",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/7_The_Desert_Awaits.mp3",
  },
  {
    id: "8",
    title: "Dust to Dust",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/8_New_Dust_to_Dust.mp3",
  },
  {
    id: "9",
    title: "Before the Storm",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/9_Before_The_Storm.mp3",
  },
  {
    id: "10",
    title: "In the Shadows",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/10_In_The_Shadows.mp3",
  },
  {
    id: "11",
    title: "Shelter from the Storm",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/11_Shelter_from_the_Storm.mp3",
  },
  {
    id: "12",
    title: "Disembodied Spirits",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/12_Disembodied_Spirits.mp3",
  },
  {
    id: "13",
    title: "Cave of Time",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/13_Cave_of_Time.mp3",
  },
  {
    id: "14",
    title: "Protean Fields",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/14_Protean_Fields.mp3",
  },
  {
    id: "15",
    title: "Alien Machine Shop",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/15_Alien_Machine_Shop.mp3",
  },
  {
    id: "16",
    title: "Busy Space Port",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/16_Busy_Space_Port.mp3",
  },
  {
    id: "17",
    title: "Alien Night Club",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/17_Alien_Night_Club.mp3",
  },
  {
    id: "18",
    title: "House on the Hill",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/18_House_on_the_Hill.mp3",
  },
  {
    id: "19",
    title: "Age of Sail",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/19_Age_of_Sail.mp3",
  },
  {
    id: "20",
    title: "Dark Continent",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/20_Dark_Continent_aa.mp3",
  },
  {
    id: "21",
    title: "Derelict Freighter",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/21_Derelict_Freighter.mp3",
  },
  {
    id: "22",
    title: "True West",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/22_True_West_a.mp3",
  },
  {
    id: "23",
    title: "The Slaughtered Ox",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/23_The_Slaughtered_Ox.mp3",
  },
  {
    id: "24",
    title: "Forbidden Galaxy!",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/24_Forbidden_Galaxy.mp3",
  },
  {
    id: "25",
    title: "Deep Space EVA",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/25_Deep_Space_EVA.mp3",
  },
  {
    id: "26",
    title: "Uncommon Valor",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/26_Uncommon_Valor_a.mp3",
  },
  {
    id: "27",
    title: "Xingu Nights",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/27_Xingu_Nights.mp3",
  },
  {
    id: "28",
    title: "Nephilim Labs FE",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/28_Nephilim_Labs_FE.mp3",
  },
  {
    id: "29",
    title: "Kaltoran Craft FE",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/29_Kaltoran_Craft_FE.mp3",
  },
  {
    id: "30",
    title: "Los Vangeles 3030",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/30_Los_Vangeles_3030.mp3",
  },
  {
    id: "31",
    title: "Frozen Wastes",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/31_Frozen_Wastes.mp3",
  },
  {
    id: "32",
    title: "City and the City",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/32_City_and_the_City.mp3",
  },
  {
    id: "33",
    title: "Far Above the World",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/33_Far_Above_the_World.mp3",
  },
  {
    id: "34",
    title: "Clash of Kings",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/34_Clash_of_Kings.mp3",
  },
  {
    id: "35",
    title: "Swamplandia",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/35_Swamplandia.mp3",
  },
  {
    id: "36",
    title: "Down by the Sea",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/36_Down_by_the_Sea.mp3",
  },
  {
    id: "37",
    title: "Catacombs",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/37_Catacombs.mp3",
  },
  {
    id: "38",
    title: "Into the Deep",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/38_Into_the_Deep.mp3",
  },
  {
    id: "39",
    title: "Temple of the Eye",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/39_Temple_of_the_Eye.mp3",
  },
  {
    id: "40",
    title: "The Long Rain",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/40_The_Long_Rain.mp3",
  },
  {
    id: "41",
    title: "Starship Bridge",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/41_Starship_Bridge.mp3",
  },
  {
    id: "42",
    title: "Rise of the Ancients",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/42_Rise_of_the_Ancients.mp3",
  },
  {
    id: "43",
    title: "Dome City Center",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/43_Dome_City_Center.mp3",
  },
  {
    id: "44",
    title: "Victorian London",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/44_Victorian_London.mp3",
  },
  {
    id: "45",
    title: "Samurai HQ",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/45_Samurai_HQ.mp3",
  },
  {
    id: "46",
    title: "Cathedral",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/46_Cathedral.mp3",
  },
  {
    id: "47",
    title: "There be Dragons!",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/47_There_be_Dragons.mp3",
  },
  {
    id: "48",
    title: "Overland with Oxen",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/48_Overland_with_Oxen.mp3",
  },
  {
    id: "49",
    title: "Goblin's Cave",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/49_Goblin's_Cave.mp3",
  },
  {
    id: "50",
    title: "Super Hero!",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/50_Super_Hero.mp3",
  },
  {
    id: "51",
    title: "Woodland Campsite",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/51_Woodland_Campsite.mp3",
  },
  {
    id: "52",
    title: "Warehouse 13",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/52_Warehouse_13.mp3",
  },
  {
    id: "53",
    title: "Strangers on a Train",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/53_Strangers_on_a_Train.mp3",
  },
  {
    id: "54",
    title: "Mountain Tavern",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/54_Mountain_Tavern.mp3",
  },
  {
    id: "55",
    title: "Ice Cavern",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/55_Ice_Cavern.mp3",
  },
  {
    id: "56",
    title: "Medieval Town",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/56_Medieval_Town.mp3",
  },
  {
    id: "57",
    title: "Colosseum",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/57_Colosseum.mp3",
  },
  {
    id: "58",
    title: "Terror",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/58_Terror.mp3",
  },
  {
    id: "59",
    title: "Dinotopia",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/59_Dinotopia.mp3",
  },
  {
    id: "60",
    title: "Dark and Stormy",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/60_Dark_and_Stormy.mp3",
  },
  {
    id: "61",
    title: "Orbital Platform",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/61_Orbital_Platform.mp3",
  },
  {
    id: "62",
    title: "Middle Earth:Dawn",
    category: "Tabletop Audio",
    url: "https://sounds.tabletopaudio.com/62_Middle_Earth_Dawn.mp3",
  },
];

export function GET() {
  return NextResponse.json(sounds);
}
