import "./globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { NextAuthProvider } from "@/providers/NextAuthProvider"
import { SessionProvider } from "next-auth/react"

import { AudioPlayerProvider } from "@/hooks/context/sounds/use-audio-player"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="dark" lang="en">
      <AudioPlayerProvider>
        <NextAuthProvider>
          <body className={inter.className}>{children}</body>
        </NextAuthProvider>
      </AudioPlayerProvider>
    </html>
  )
}
